const data = {
    English: {
        signIn: "Sign in",
        signInIf: "If you don't have an account register",
        youCan: "You can",
        registerHere: "Register here !",
        Email: "Email",
        Password: "Password",
        EnterEmail: "Enter your email address",
        EnterPassword: "Enter your email password",
        RememberMe: "Remember me",
        Login: "Login",
        ForgotPass: "Forgot Password !",
        OrContinue: "or continue with",
        GGAccount: "Google account",
        Profile: "Profile",
        CreateAt: "Created at",
        Starttime: "Start time",
        EsTime: "Estimated end time",
        ETime: "End time",
        JoinMember: "Joined member",
        Project: "Project",
        People: "People",
        Templates: "Templates",
        Setting: "Setting",
        DarkMode: "Darkmode",
        Language: "Language",
        Free: "Free",
        VIP: "Premium",
        usetool: "use tool",
        createreports: "create reports",
        addData: "unlimited add data sources",
        multipleprojects: "multiple projects",
        ///////
        limitPro: "unlimited projects",
        invite: "unlimited invite member",

        nolimitreports: "unlimited reports",
        used: "Used",
        getPremiun: "Get Premium",
        English: "English",
        Vietnamese: "Vietnamese",
        DataSource: "Data Sources",
        userSource: "User Sources",
        sampleSource: "Samples",
        dataCreate: "Date created: ",
        lastModi: "Last modified: ",
        createBy: "Created by: ",
        people: "People",
        manager: "Manager",
        member: "Member",
        templates: "Templates",
        createDate: "Created Date: ",
        gallery: "Gallery",
        importData: "Import data",
        importCSV: "Import csv file",
        importXLSX: "Import XLSX file",
        importJSOM: "Import JON file",
        connectToDB: "Connect to database",
        sampleModel: "Sample Model",
        createModel: "Create a new model",
        models: "Models"




    },
    Vietnamese: {
        signIn: "Đăng nhập",
        signInIf: "Nếu bạn chưa có tài khoản",
        youCan: "Bạn có thể",
        registerHere: "Đăng kí ngay !",
        Email: "Email",
        Password: "Mật khẩu",
        EnterEmail: "Nhập email của bạn",
        EnterPassword: "Nhập mật khẩu",
        RememberMe: "Nhớ mật khẩu",
        Login: "Đăng nhập",
        ForgotPass: "Quên mật khẩu !",
        OrContinue: "hoặc tiếp tục với",
        GGAccount: "tài khoản Google",
        Profile: "Trang cá nhân",
        CreateAt: "Thời gian tạo",
        Starttime: "Thời gian bắt đầu",
        EsTime: "Dự đoán kết thúc",
        ETime: "Thời gian kết thúc",
        JoinMember: "Số người tham gia",
        Project: "Các dự án",
        People: "Mọi người",
        Templates: "Mẫu báo cáo",
        Setting: "Cài đặt",
        DarkMode: "Giao diện tối",
        Language: "Ngôn ngữ",
        Free: "Miễn phí",
        VIP: "VIP",
        usetool: "Sử dụng tool",
        createreports: "Tạo báo cáo",
        addData: "Không giới hạn thêm nguồn dữ liệu",
        sharereports: "Chia sẻ nhiều báo cáo",
        limitPro: "Không giới hạn dự án",
        invite: "Không giới hạn mời thành viên",
        nolimitreports: "Không giới hạn số lượng báo cáo",
        used: "Đã sử dụng",
        getPremiun: "Nâng cấp VIP",
        English: "Tiếng Anh",
        Vietnamese: "Tiếng Việt",
        DataSource: "Nguồn dữ liệu",
        userSource: "Dữ liệu người dùng",
        sampleSource: "Dữ liệu mẫu",
        dataCreate: "Ngày tạo: ",
        lastModi: "Gần nhất: ",
        createBy: "Tạo bởi: ",
        people: "Mọi người",
        manager: "Quản lí",
        member: "Thành viên",
        gallery: "Thư viện",
        importData: "Thêm dữ liệu",
        importCSV: "Thêm file .csv",
        importXLSX: "Thêm file .XLSX",
        importJSOM: "Thêm file .JSON",
        connectToDB: "Kết nối database",
        sampleModel: "Mẫu Model",
        createModel: "Tạo một model mới",
        models: "Danh sách các model"
    }
};

export {
    data
}