const data = {
    English: {
        signIn: "Sign in",
        signInIf: "If you don't have an account register",
        youCan: "You can",
        registerHere: "Register here !",
        Email: "Email",
        Password: "Password",
        EnterEmail: "Enter your email address",
        EnterPassword: "Enter your email password",
        RememberMe: "Remember me",
        Login: "Login",
        ForgotPass: "Forgot Password !",
        OrContinue: "or continue with",
        GGAccount: "Google account",
        Profile: "Profile",
        CreateAt: "Created at",
        Starttime: "Start time",
        EsTime: "Estimated end time",
        ETime: "End time",
        ETime: "End Time",
        JoinMember: "Joined member",
        Project: "Project",
        People: "People",
        Templates: "Templates",
        Setting: "Setting",
        DarkMode: "Darkmode",
        Language: "Language",
        Free: "Free",
        VIP: "Premium",
        usetool: "use tool",
        createreports: "create reports",
        sharereports: "share reports",
        multipleprojects: "multiple projects",
        blockads: "block ads",
        nolimitreports: "nolimit reports",
        used: "Used",
        getPremiun: "Get Premium",
        English: "English",
        Vietnamese: "Vietnamese"



    },
    Vietnamese: {
        signIn: "Đăng nhập",
        signInIf: "Nếu bạn chưa có tài khoản",
        youCan: "Bạn có thể",
        registerHere: "Đăng kí ngay !",
        Email: "Email",
        Password: "Mật khẩu",
        EnterEmail: "Nhập email của bạn",
        EnterPassword: "Nhập mật khẩu",
        RememberMe: "Nhớ mật khẩu",
        Login: "Đăng nhập",
        ForgotPass: "Quên mật khẩu !",
        OrContinue: "hoặc tiếp tục với",
        GGAccount: "tài khoản Google",
        Profile: "Trang cá nhân",
        CreateAt: "Thời gian tạo",
        Starttime: "Thời gian bắt đầu",
        EsTime: "Dự đoán kết thúc",
        ETime: "Thời gian kết thúc",
        ETime: "Thời gian kết thúc",
        JoinMember: "Số người tham gia",
        Project: "Các dự án",
        People: "Mọi người",
        Templates: "Mẫu báo cáo",
        Setting: "Cài đặt",
        DarkMode: "Giao diện tối",
        Language: "Ngôn ngữ",
        Free: "Miễn phí",
        VIP: "VIP",
        usetool: "Sử dụng tool",
        createreports: "Tạo nhiều dự án",
        sharereports: "Chia sẻ nhiều báo cáo",
        multipleprojects: "Làm việc cùng lúc nhiều dự án",
        blockads: "Chặn quảng cáo",
        nolimitreports: "Không giới hạn số lượng báo cáo",
        used: "Đã sử dụng",
        getPremiun: "Nâng cấp VIP",
        English: "Tiếng Anh",
        Vietnamese: "Tiếng Việt"
    }
};

export {
    data
}